Kanq.ItcastOA.WebApp/Controllers/ActionInfoController.cs
using Kanq.ItcastOA.Common;
using Kanq.ItcastOA.IBLL;
using Kanq.ItcastOA.Model;
using Kanq.ItcastOA.Model.Search;
using Kanq.ItcastOA.WebApp.Models.EnumType;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace Kanq.ItcastOA.WebApp.Controllers
{
    public class ActionInfoController : Controller
    {

        public IActionInfoService ActionInfoService { get; set; }
        public IRoleInfoService RoleInfoService { get; set; }

        short delFlag = (short)DeleteEnumType.Normal;

        // GET: ActionInfo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetActionInfoList(int page, int rows, string ActionInfoName, string Url)
        {
            //int totalCount = 0;
            ActionInfoSearch actionInfoSearch = new ActionInfoSearch()
            {
                PageIndex = page,
                PageSize = rows,
                ActionInfoName = ActionInfoName,
                Url = Url,
                //TotalCount = totalCount
            };
            var ActionInfoList = ActionInfoService.LoadSerachEntities(actionInfoSearch, delFlag).Select(
                u =>
                new
                {
                    u.ID,
                    u.ActionInfoName,
                    u.Url,
                    u.HttpMethod,
                    u.Remark,
                    u.MenuIcon,
                    u.IsMenu,
                    u.SubTime,
                    u.ModifiedOn,
                    u.Sort
                });
            //var ActionInfoList = ActionInfoService.LoadPageEntities(page, rows, out totalCount, u => u.DelFlag == delFlag, u => u.ID).Select(u => new { ID = u.ID, UName = u.UName, UPwd = u.UPwd, SubTime = u.SubTime, Remark = u.Remark });
            string data = WebCommon.GetJsonList(actionInfoSearch.TotalCount, ActionInfoList);
            return Content(data);
        }

        public ActionResult DeleteActionInfo(string idList)
        {
            string[] strs = idList.Split(',');
            List<int> list = new List<int>();
            foreach (string item in strs)
            {
                list.Add(Convert.ToInt32(item));
            }
            if (ActionInfoService.DeleteEntitys(list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        public ActionResult AddActionInfo(ActionInfo actionInfo)
        {
            actionInfo.DelFlag = (short)DeleteEnumType.Normal;
            actionInfo.SubTime = DateTime.Now;
            actionInfo.ModifiedOn = DateTime.Now;
            actionInfo.IsMenu = Request["IsMenu"] == null ? false : true;
            ActionInfoService.AddEntity(actionInfo);
            return Content("ok");
        }

        public ActionResult ShowActionInfo(int id)
        {
            ActionInfo actionInfo = ActionInfoService.LoadEntities(u => u.ID == id).FirstOrDefault();
            return Content(WebCommon.GetJson(actionInfo));
        }

        public ActionResult EditActionInfo(ActionInfo actionInfo)
        {
            actionInfo.ModifiedOn = DateTime.Now;
            if (ActionInfoService.EditEntity(actionInfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        public ActionResult UploadImage()
        {
            var file = Request.Files["fileMenuIcon"];
            string dirPath = "/UploadFiles/UploadImages";
            string fullPath = Path.Combine(dirPath, Guid.NewGuid().ToString() + "-" + Path.GetFileName(file.FileName));
            if (!Directory.Exists(Request.MapPath(dirPath)))
            {
                Directory.CreateDirectory(Request.MapPath(dirPath));
            }
            file.SaveAs(Request.MapPath(fullPath));
            return Content(fullPath);
        }

        public ActionResult SetRole(int id)
        {
            ActionInfo actionInfo = ActionInfoService.LoadEntities(t => t.ID == id).FirstOrDefault();
            ViewBag.allRoleInfos = RoleInfoService.LoadEntities(t => t.DelFlag == delFlag).ToList();
            ViewBag.existsRoleIds = actionInfo.RoleInfo.Select(t => t.ID).ToList();
            return View(actionInfo);
        }

        public ActionResult ProcessSetRole(int actionId)
        {
            List<int> roleIds = new List<int>();
            foreach (var key in Request.Form.AllKeys)
            {
                if (key.StartsWith("ckb_"))
                {
                    int roleId = int.Parse(key.Replace("ckb_", ""));
                    roleIds.Add(roleId);
                }
            }
            ActionInfoService.setRole(actionId, roleIds);
            return Content("ok");
        }

    }
}

Kanq.ItcastOA.WebApp/Views/ActionInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
        @Styles.Render("~/Content/easyui")
    <style>
    </style>
        @Scripts.Render("~/bundles/jquery", "~/bundles/easyui")
        <script src="~/Scripts/MyAjaxForm.js"></script>
    <script>
        $(function () {
            $("#AddDiv").css("display", "none");
            $("#EditDiv").css("display", "none");
            $("#SetRoleDiv").css("display", "none");
            loadDataGrid();
            $("#btnSearch").linkbutton({
                text: "查询",
                iconCls: "icon-search",
                onClick: function () {
                    reloadData();
                }
            });

            bindUploadBtnClick();
        });

        function bindUploadBtnClick() {
            $("#btnUploadFile").click(function () {
                $("#AddForm").ajaxSubmit({
                    url: "/ActionInfo/UploadImage",
                    type:"Post",
                    success: function (data) {
                        $("#MenuIcon").val(data);
                        $("#uploadImage").html("<img src='" + data + "' width='100px' height='100px' />");
                    },
                });
            });
        }

        function afterSetRole() {
            $.messager.alert("提示", "角色设置成功", "error");
            $("#SetRoleDiv").dialog("close");
        }

        function reloadData() {
            $("#tt").datagrid("load", {
                ActionInfoName: $("#txtActionInfoName").val(),
                Url: $("#txtUrl").val()
            });
        }

        function loadDataGrid() {
            /// <summary>加载数据列表</summary>
            $("#tt").datagrid({
                toolbar: [{
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: 'AddActionInfo'
                }, {
                    id: 'btnEdit',
                    text: '修改',
                    iconCls: 'icon-edit',
                    handler: 'EditActionInfo'
                }, {
                    id: 'btnDel',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: 'DelActionInfo'
                }, {
                    id: 'btnSetRole',
                    text: '设置角色',
                    iconCls: 'icon-undo',
                    handler: 'SetRole'
                }],
                pagination: true,//分页
                pageSize: 10,//每页记录数
                pageList: [10, 20],//可选择的每页记录数
                height: 500,
                url: "/ActionInfo/GetActionInfoList",
                //fit: true,
                //queryParams: { action: "ShowList" },
                columns:
                [[
                    { field: 'ck', checkbox: true },
                    { field: 'ID', title: '编号', align: "center", width: 80 },
                    { field: 'ActionInfoName', title: '权限名', align: "center", width: 80},
                    { field: 'Url', title: 'Url', align: "center", width: 80 },
                    { field: 'HttpMethod', title: '请求方式', align: "center", width: 80 },
                    { field: 'Remark', title: '备注', align: "center", width: 150 },
                    {
                        field: 'MenuIcon', title: '菜单图标', align: "center", width: 150,
                        formatter: function (value, row, index) {
                            return "<img src='"+value+"' width='100px' height='100px' />"
                        }
                    },
                    {
                        field: 'IsMenu', title: '菜单显示', align: "center", width: 150,
                        formatter: function (value, row, index) {
                            return value == true ? "是" : "否";
                        }
                    },
                    { field: 'SubTime', title: '注册时间', align: "center", width: 150 },
                    { field: 'ModifiedOn', title: '修改时间', align: "center", width: 150 },
                    { field: 'Sort', title: '排序字段', align: "center", width: 150 }
                ]],
                striped: true,//显示条纹
                singleSelect: false//单选模式
            })
        };

        //设置用户角色
        function SetRole() {
            var rows = $("#tt").datagrid("getSelections");
            if (rows.length != 1) {
                $.messager.alert("提示", "请选择一行进行设置", "error");
                return;
            }
            $("#SetRoleDiv").css("display", "");
            var id = rows[0].ID;
            $("#SetRoleIframe").attr("src", "/ActionInfo/SetRole/" + id);
            $("#SetRoleDiv").dialog({
                //width: 750,
                //height: 350,
                title: "设置权限",
                collapsible: false,
                maximizable: false,
                resizable: false,
                modal: true,
                onClose: function () {
                },
                toolbar: [{
                    text: '保存',
                    iconCls: 'icon-save',
                    handler: function () {
                        $("#SetRoleIframe")[0].contentWindow.submitForm();
                    }
                }],
            });
        }

        function EditActionInfo() {
            var rows = $("#tt").datagrid("getSelections");
            if (rows.length != 1) {
                $.messager.alert("提示", "请选择一行进行修改", "error");
                return;
            }
            var id = rows[0].ID;
            $("#EditDiv").css("display", "block");
            $("#EditForm").form("load", "/ActionInfo/ShowActionInfo/" + id);
            $("#EditDiv").dialog({
                //width: 750,
                //height: 350,
                title: "修改权限",
                collapsible: false,
                maximizable: false,
                resizable: false,
                modal: true,
                onClose: function () {
                    $("#EditForm").form("clear");
                },
                toolbar: [{
                    text: '保存',
                    iconCls: 'icon-save',
                    handler: function () {
                        $("#EditForm").form("submit", {
                            url: "/ActionInfo/EditActionInfo",
                            onSubmit: function () {
                                return $("#EditForm").form("validate");
                            },
                            success: function (data) {
                                if (data && data == "ok") {
                                    $("#tt").datagrid("reload");
                                    $("#EditDiv").dialog("close");
                                }
                                else {
                                    $.messager.alert("警告", "权限修改失败", "error");
                                }
                            }
                        });
                    }
                }],
            });
        }

        function AddActionInfo() {
            $("#AddDiv").css("display", "block");
            $("#AddDiv").dialog({
                //width: 750,
                //height: 350,
                title: "添加权限",
                collapsible: false,
                maximizable: false,
                resizable: false,
                modal: true,
                onClose: function () {
                    $("#AddDiv").form("clear");
                },
                toolbar: [{
                    text: '保存',
                    iconCls: 'icon-save',
                    handler: function () {
                        $("#AddForm").form("submit", {
                            url: "/ActionInfo/AddActionInfo",
                            onSubmit: function () {
                                return $("#AddForm").form("validate");
                            },
                            success: function (data) {
                                if (data && data == "ok") {
                                    $("#tt").datagrid("reload");
                                    $("#AddDiv").dialog("close");
                                }
                                else {
                                    $.messager.alert("警告", "权限添加失败", "error");
                                }
                            }
                        });
                    }
                }],
            });
        }

        function DelActionInfo() {
            var rows = $("#tt").datagrid("getSelections");
            if (rows.length == 0) {
                $.messager.alert("提示", "请选择一行进行删除", "error");
                return;
            }
            $.messager.confirm("提示", "确定要删除吗？", function (r) {
                if (r) {
                    var idList = [];
                    var rowsLength = rows.length;
                    for (var i = 0; i < rowsLength; i++) {
                        idList.push(rows[i].ID);
                    }
                    $.post("/ActionInfo/DeleteActionInfo", { idList: idList.join(",") }, function (data) {
                        if (data == "ok") {
                            $("#tt").datagrid("reload");
                        }
                        else {
                            $.messager.alert("提示", "删除失败", "error");
                        }
                    });
                }
            });
        }
    </script>
</head>
<body>
    <div id="master">
        <div id="Search">
            权限名:<input type="text" id="txtActionInfoName" name="ActionInfoName" />&nbsp;&nbsp;&nbsp;
            URL:<input type="text" id="txtUrl" name="Url" />
            <a id="btnSearch"></a>
        </div>
        <div>
            <table id="tt"></table>
        </div>
    </div>
    <!--新增权限-->
    <div id="AddDiv">
        <form id="AddForm" method="post" enctype="multipart/form-data">
            <table>
                <tr>
                    <td>权限名:</td>
                    <td><input type="text" name="ActionInfoName" /></td>
                </tr>
                <tr>
                    <td>Url:</td>
                    <td><input type="text" name="Url" /></td>
                </tr>
                <tr>
                    <td>请求方式</td>
                    <td>
                        <select name="HttpMethod">
                            <option value="Get">Get</option>
                            <option value="Post">Post</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>菜单图标:</td>
                    <td>
                        <input type="hidden" id="MenuIcon" name="MenuIcon" />
                        <input type="file" name="fileMenuIcon" />
                        <input id="btnUploadFile" type="button"  value="上传" />
                        <div id="uploadImage"></div>
                    </td>
                </tr>
                <tr>
                    <td>菜单显示:</td>
                    <td><input type="checkbox" name="IsMenu"/></td>
                </tr>
                <tr>
                    <td>排序字段:</td>
                    <td><input type="text" name="Sort" /></td>
                </tr>
                <tr>
                    <td>备注:</td>
                    <td><input type="text" name="Remark" /></td>
                </tr>
            </table>
        </form>
    </div>

    <!--修改权限-->
    <div id="EditDiv">
        <form id="EditForm" method="post">
            <input type="hidden" name="ID" />
            <input type="hidden" name="DelFlag" />
            <input type="hidden" name="SubTime" />
            <table>
                <tr>
                    <td>权限名:</td>
                    <td><input type="text" name="ActionInfoName" /></td>
                </tr>
                <tr>
                    <td>Url:</td>
                    <td><input type="text" name="Url" /></td>
                </tr>
                <tr>
                    <td>请求方式</td>
                    <td>
                        <select name="HttpMethod">
                            <option value="Get">Get</option>
                            <option value="Post">Post</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>菜单图标:</td>
                    <td><input type="text" name="MenuIcon" /></td>
                </tr>
                <tr>
                    <td>菜单显示:</td>
                    <td><input type="checkbox" name="IsMenu" /></td>
                </tr>
                <tr>
                    <td>排序字段:</td>
                    <td><input type="text" name="Sort" /></td>
                </tr>
                <tr>
                    <td>备注:</td>
                    <td><input type="text" name="Remark" /></td>
                </tr>
            </table>
        </form>
    </div>

    <!--设置角色-->
    <div id="SetRoleDiv">
        <iframe id="SetRoleIframe" src="javascript:void(0)"></iframe>
    </div>
</body>
</html>

Kanq.ItcastOA.WebApp/Views/ActionInfo/SetRole.cshtml
@using Kanq.ItcastOA.Model
@model Kanq.ItcastOA.Model.ActionInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetRole</title>
    <script src="~/Scripts/jquery-1.12.4.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function submitForm() {
            $("form").submit();
        }

        function afterSetRole(data) {
            if (data == "ok") {
                window.parent.window.afterSetRole();
            }
        }
    </script>
</head>
<body>
    <div>
        <h2>当前给用户：@Model.ActionInfoName 设置角色</h2>
        <hr />
        @{
            List<RoleInfo> allRoleInfos = ViewBag.allRoleInfos;
            List<int> existsRoleIds = ViewBag.existsRoleIds;
            using (Ajax.BeginForm("ProcessSetRole", "ActionInfo", new AjaxOptions() { OnSuccess = "afterSetRole" }))
            {
                <input type="hidden" name="actionId" value="@Model.ID" />
                foreach (var roleInfo in allRoleInfos)
                {
                    string str = "ckb_" + roleInfo.ID;
                    if (existsRoleIds.Contains(roleInfo.ID))
                    {
                        <input type="checkbox" checked="checked" name="@str" id="@str" value="@str" />

                    }
                    else
                    {
                        <input type="checkbox" name="@str" id="@str" value="@str" />
                    }
                    <label for="@str">@roleInfo.RoleName</label>
                }
            }
        }
    </div>
</body>
</html>