Kanq.ItcastOA.WebApp/Controllers/UserInfoController.cs
using Kanq.ItcastOA.Common;
using Kanq.ItcastOA.IBLL;
using Kanq.ItcastOA.Model;
using Kanq.ItcastOA.Model.Search;
using Kanq.ItcastOA.WebApp.Models;
using Kanq.ItcastOA.WebApp.Models.EnumType;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kanq.ItcastOA.WebApp.Controllers
{
    public class UserInfoController :Controller
    {
        public IUserInfoService userInfoService { get; set; }
        public IRoleInfoService RoleInfoService { get; set; }

        short delFlag = (short)DeleteEnumType.Normal;
        // GET: UserInfo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetUserInfoList(int page, int rows, string UName, string Remark)
        {
            //int totalCount = 0;
            UserInfoSearch userInfoSearch = new UserInfoSearch()
            {
                PageIndex = page,
                PageSize = rows,
                UName = UName,
                Remark = Remark,
                //TotalCount = totalCount
            };
            var userInfoList = userInfoService.LoadSerachEntities(userInfoSearch, delFlag).Select(u => new { ID = u.ID, UName = u.UName, UPwd = u.UPwd, SubTime = u.SubTime, Remark = u.Remark });
            //var userInfoList = userInfoService.LoadPageEntities(page, rows, out totalCount, u => u.DelFlag == delFlag, u => u.ID).Select(u => new { ID = u.ID, UName = u.UName, UPwd = u.UPwd, SubTime = u.SubTime, Remark = u.Remark });
            string data = WebCommon.GetJsonList(userInfoSearch.TotalCount, userInfoList);
            return Content(data);
        }

        public ActionResult DeleteUserInfo(string idList)
        {
            string[] strs = idList.Split(',');
            List<int> list = new List<int>();
            foreach (string item in strs)
            {
                list.Add(Convert.ToInt32(item));
            }
            if (userInfoService.DeleteEntitys(list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        public ActionResult AddUserInfo(UserInfo userInfo)
        {
            userInfo.DelFlag = (short)DeleteEnumType.Normal;
            userInfo.SubTime = DateTime.Now;
            userInfo.ModifiedOn = DateTime.Now;
            userInfoService.AddEntity(userInfo);
            return Content("ok");
        }

        public ActionResult ShowUserInfo(int id)
        {
            UserInfo userInfo = userInfoService.LoadEntities(u => u.ID == id).FirstOrDefault();
            return Content(WebCommon.GetJson(userInfo));
        }

        public ActionResult EditUserInfo(UserInfo userInfo)
        {
            userInfo.ModifiedOn = DateTime.Now;
            if (userInfoService.EditEntity(userInfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        public ActionResult SetRole(int id)
        {
            UserInfo userInfo = userInfoService.LoadEntities(t => t.ID == id).FirstOrDefault();
            ViewBag.allRoleInfos = RoleInfoService.LoadEntities(t => t.DelFlag == delFlag).ToList();
            ViewBag.existsRoleIds = userInfo.RoleInfo.Select(t => t.ID).ToList();
            return View(userInfo);
        }

        public ActionResult ProcessSetRole(int userId)
        {
            List<int> roleIds = new List<int>();
            foreach (var key in Request.Form.AllKeys)
            {
                if (key.StartsWith("ckb_"))
                {
                    int roleId = int.Parse(key.Replace("ckb_", ""));
                    roleIds.Add(roleId);
                }
            }
            userInfoService.setRole(userId, roleIds);
            return Content("ok");
        }

        public ActionResult SetAction(int id)
        {
            UserInfo userInfo = userInfoService.LoadEntities(t => t.ID == id).FirstOrDefault();
            //ViewBag.allRoleInfos = RoleInfoService.LoadEntities(t => t.DelFlag == delFlag).ToList();
            //ViewBag.existsRoleIds = userInfo.RoleInfo.Select(t => t.ID).ToList();
            return View(userInfo);
        }
    }
}

Kanq.ItcastOA.WebApp/Views/UserInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/easyui")
    <style>
    </style>
    @Scripts.Render("~/bundles/jquery", "~/bundles/easyui")
    <script>
        $(function () {
            $("#AddDiv").css("display", "none");
            $("#EditDiv").css("display", "none");
            $("#SetRoleDiv").css("display", "none");
            $("#SetActionDiv").css("display", "none");
            loadDataGrid();
            $("#btnSearch").linkbutton({
                text: "查询",
                iconCls: "icon-search",
                onClick: function () {
                    reloadData();
                }
            });
        });

        function afterSetRole() {
            $.messager.alert("提示", "角色设置成功", "error");
            $("#SetRoleDiv").dialog("close");
        }

        function reloadData() {
            $("#tt").datagrid("load", {
                Uname: $("#txtUname").val(),
                Remark: $("#txtRemark").val()
            });
        }

        function loadDataGrid() {
            /// <summary>加载数据列表</summary>
            $("#tt").datagrid({
                toolbar: [{
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: 'AddUserInfo'
                }, {
                    id: 'btnEdit',
                    text: '修改',
                    iconCls: 'icon-edit',
                    handler: 'EditUserInfo'
                }, {
                    id: 'btnDel',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: 'DelUserInfo'
                }, {
                    id: 'btnSetRole',
                    text: '设置角色',
                    iconCls: 'icon-undo',
                    handler: 'SetRole'
                }, {
                    id: 'btnSetAction',
                    text: '设置特殊权限',
                    iconCls: 'icon-undo',
                    handler: 'SetAction'
                }],
                pagination: true,//分页
                pageSize: 10,//每页记录数
                pageList: [10, 20],//可选择的每页记录数
                height: 500,
                url: "/UserInfo/GetUserInfoList",
                //fit: true,
                //queryParams: { action: "ShowList" },
                columns:
                [[
                    { field: 'ck', checkbox: true },
                    { field: 'ID', title: '编号', align: "center", width: 80 },
                    { field: 'UName', title: '用户名', align: "center", width: 80 },
                    { field: 'UPwd', title: '密码', align: "center", width: 80 },
                    { field: 'SubTime', title: '注册时间', align: "center", width: 80 },
                    { field: 'Remark', title: '备注', align: "center", width: 150 }
                ]],
                striped: true,//显示条纹
                singleSelect: false//单选模式
            })
        };

        //设置用户角色
        function SetRole() {
            var rows = $("#tt").datagrid("getSelections");
            if (rows.length != 1) {
                $.messager.alert("提示", "请选择一行进行设置", "error");
                return;
            }
            $("#SetRoleDiv").css("display", "");
            var id = rows[0].ID;
            $("#SetRoleIframe").attr("src", "/UserInfo/SetRole/" + id);
            $("#SetRoleDiv").dialog({
                //width: 750,
                //height: 350,
                title: "设置权限",
                collapsible: false,
                maximizable: false,
                resizable: false,
                modal: true,
                onClose: function () {
                },
                toolbar: [{
                    text: '保存',
                    iconCls: 'icon-save',
                    handler: function () {
                        $("#SetRoleIframe")[0].contentWindow.submitForm();
                    }
                }],
            });
        }

        //设置用户特殊权限
        function SetAction() {
            var rows = $("#tt").datagrid("getSelections");
            if (rows.length != 1) {
                $.messager.alert("提示", "请选择一行进行设置", "error");
                return;
            }
            $("#SetActionDiv").css("display", "");
            var id = rows[0].ID;
            $("#SetActionIframe").attr("src", "/UserInfo/SetAction/" + id);
            $("#SetActionDiv").dialog({
                //width: 750,
                //height: 350,
                title: "设置权限",
                collapsible: false,
                maximizable: false,
                resizable: false,
                modal: true,
                onClose: function () {
                },
                toolbar: [{
                    text: '保存',
                    iconCls: 'icon-save',
                    handler: function () {
                        $("#SetActionIframe")[0].contentWindow.submitForm();
                    }
                }],
            });
        }

        function EditUserInfo() {
            var rows = $("#tt").datagrid("getSelections");
            if (rows.length != 1) {
                $.messager.alert("提示", "请选择一行进行修改", "error");
                return;
            }
            var id = rows[0].ID;
            $("#EditDiv").css("display", "block");
            $("#UPwdE").validatebox({
                required: true,
                missingMessage: "密码不能为空"
            });
            $("#EditForm").form("load", "/UserInfo/ShowUserInfo/"+id);
            $("#EditDiv").dialog({
                //width: 750,
                //height: 350,
                title: "修改用户",
                collapsible: false,
                maximizable: false,
                resizable: false,
                modal: true,
                onClose: function () {
                    $("#EditForm").form("clear");
                },
                toolbar: [{
                    text: '保存',
                    iconCls: 'icon-save',
                    handler: function () {
                        $("#EditForm").form("submit", {
                            url: "/UserInfo/EditUserInfo",
                            onSubmit: function () {
                                return $("#EditForm").form("validate");
                            },
                            success: function (data) {
                                if (data && data == "ok") {
                                    $("#tt").datagrid("reload");
                                    $("#EditDiv").dialog("close");
                                }
                                else {
                                    $.messager.alert("警告", "用户修改失败", "error");
                                }
                            }
                        });
                    }
                }],
            });
        }

        function AddUserInfo() {
            $("#AddDiv").css("display", "block");
            $("#UPwd").validatebox({
                required: true,
                missingMessage:"密码不能为空"
            });
            $("#AddDiv").dialog({
                //width: 750,
                //height: 350,
                title: "添加用户",
                collapsible: false,
                maximizable: false,
                resizable: false,
                modal: true,
                onClose: function () {
                    $("#AddDiv").form("clear");
                },
                toolbar: [{
                    text: '保存',
                    iconCls: 'icon-save',
                    handler: function () {
                        $("#AddForm").form("submit", {
                            url: "/UserInfo/AddUserInfo",
                            onSubmit:function () {
                                return $("#AddForm").form("validate");
                            },
                            success: function (data) {
                                if (data && data == "ok") {
                                    $("#tt").datagrid("reload");
                                    $("#AddDiv").dialog("close");
                                }
                                else {
                                    $.messager.alert("警告", "用户添加失败", "error");
                                }
                            }
                        });
                    }
                }],
            });
        }

        function DelUserInfo() {
            var rows = $("#tt").datagrid("getSelections");
            if (rows.length == 0) {
                $.messager.alert("提示", "请选择一行进行删除", "error");
                return;
            }
            $.messager.confirm("提示", "确定要删除吗？", function (r) {
                if (r) {
                    var idList = [];
                    var rowsLength = rows.length;
                    for (var i = 0; i < rowsLength; i++) {
                        idList.push(rows[i].ID);
                    }
                    $.post("/UserInfo/DeleteUserInfo", { idList: idList.join(",") }, function (data) {
                        if (data == "ok") {
                            $("#tt").datagrid("reload");
                        }
                        else {
                            $.messager.alert("提示", "删除失败", "error");
                        }
                    });
                }
            });
        }
    </script>
</head>
<body>
    <div id="master">
        <div id="Search">
            用户名:<input type="text" id="txtUname" name="Uname"/>&nbsp;&nbsp;&nbsp;
            备注:<input type="text" id="txtRemark" name="Remark"/>
            <a id="btnSearch"></a>
        </div>
        <div>
            <table id="tt"></table>
        </div>
    </div>

    <!--新增用户-->
    <div id="AddDiv">
        <form id="AddForm" method="post">
            <table>
                <tr>
                    <td>用户名:</td>
                    <td><input type="text" name="UName" /></td>
                </tr>
                <tr>
                    <td>密码:</td>
                    <td><input id="UPwd" type="text" name="UPwd" /></td>
                </tr>
                <tr>
                    <td>备注:</td>
                    <td><input type="text" name="Remark" /></td>
                </tr>
                <tr>
                    <td>排序字段:</td>
                    <td><input type="text" name="Sort" /></td>
                </tr>
            </table>
        </form>
    </div>

    <!--修改用户-->
    <div id="EditDiv">
        <form id="EditForm" method="post">
            <input type="hidden" name="ID" />
            <input type="hidden" name="DelFlag" />
            <input type="hidden" name="SubTime" />
            <table>
                <tr>
                    <td>用户名:</td>
                    <td><input type="text" name="UName" /></td>
                </tr>
                <tr>
                    <td>密码:</td>
                    <td><input id="UPwdE" type="text" name="UPwd" /></td>
                </tr>
                <tr>
                    <td>备注:</td>
                    <td><input type="text" name="Remark" /></td>
                </tr>
                <tr>
                    <td>排序字段:</td>
                    <td><input type="text" name="Sort" /></td>
                </tr>
            </table>
        </form>
    </div>

    <!--设置角色-->
    <div id="SetRoleDiv">
        <iframe id="SetRoleIframe" src="javascript:void(0)"></iframe>
    </div>

    <!--设置权限-->
    <div id="SetActionDiv">
        <iframe id="SetActionIframe" src="javascript:void(0)"></iframe>
    </div>
</body>
</html>

Kanq.ItcastOA.WebApp/Views/UserInfo/SetAction.cshtml
@model Kanq.ItcastOA.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetAction</title>
</head>
<body>
    <div>
        <h3>给用户：@Model.UName 设置权限</h3> 
    </div>
</body>
</html>

Kanq.ItcastOA.WebApp/Views/UserInfo/SetRole.cshtml
@using Kanq.ItcastOA.Model
@model Kanq.ItcastOA.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetRole</title>
    <script src="~/Scripts/jquery-1.12.4.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function submitForm() {
            $("form").submit();
        }

        function afterSetRole(data) {
            if (data == "ok") {
                window.parent.window.afterSetRole();
            }
        }
    </script>
</head>
<body>
    <div>
        <h2>当前给用户：@Model.UName 设置角色</h2>
        <hr />
        @{
            List<RoleInfo> allRoleInfos = ViewBag.allRoleInfos;
            List<int> existsRoleIds = ViewBag.existsRoleIds;
            using (Ajax.BeginForm("ProcessSetRole", "UserInfo", new AjaxOptions() { OnSuccess = "afterSetRole" }))
            {
                <input type="hidden" name="userId" value="@Model.ID" />
                foreach (var roleInfo in allRoleInfos)
                {
                    string str = "ckb_" + roleInfo.ID;
                    if (existsRoleIds.Contains(roleInfo.ID))
                    {
                        <input type="checkbox" checked="checked" name="@str" id="@str" value="@str" />

                    }
                    else
                    {
                        <input type="checkbox" name="@str" id="@str" value="@str" />
                    }
                    <label for="@str">@roleInfo.RoleName</label>
                }
            }
        }
    </div>
</body>
</html>